name: wmm
favicon: null
layout_spectrum: 0.72761903796345
typography_spectrum: 0.10491526057012379
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6224629646167159
  lightness: 0.8344895779155195
  saturation: 0.9883458118420094
  rhythmicContrast: 0.04097773879766464
purpose: []
